= What to Write About
:date: 2024-02-26

This is going to be a mostly stream of consciousness post about how I've been struggling to think of what to write for my blog. I want to write blog posts because I think it'll be good to get my thoughts out in a concrete way, but there are two main obstacles I'm facing. 

The first is a lack of specific ideas; a blog post can be about anything, and it has been hard for me to pin down anything in particular. The second is a lack of confidence; I keep doubting if what I have to say is interesting, insightful, or even just right.

Both of those obstacles can be mitigated with experience, but I'm having trouble getting the ball rolling. Maybe writing some ideas down in this blog post will help? I'm not sure, but it's worth a try.

* Going over my home server setup
* Reviewing each short story from both of Ted Chiang's collections
* Showing off my Unmatched stats dashboard
* Sharing my thoughts on big tech companies, Musk, and DOGE

I think that worked! I'm pretty happy with those ideas, and I'll try to write blog posts about them in the near future.
